services:
  postgres:
    image: postgres
    container_name: postgres_gis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_gis_data:/var/lib/postgresql/data
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.x
    container_name: geoserver_gabriel
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver_data
    volumes:
      - /home/gabriel/geoserver:/opt/geoserver_data
    restart: always
volumes:
  geoserver_data:
    driver: local
  postgres_gis_data:
    driver: local